/*PROGRAM*/
SET SERVEROUTPUT ON;
DECLARE
MARK FLOAT;
GRADE CHAR(1);
BEGIN
MARK:=&MARK;
IF MARK>=90 THEN
GRADE:='A';
ELSIF MARK<90 AND MARK>=80 THEN
GRADE:='B';
ELSIF MARK<80 AND MARK>=70 THEN
GRADE:='C';
ELSIF MARK<70 AND MARK>=60 THEN
GRADE:='D';
ELSIF MARK<60 AND MARK>=50 THEN
GRADE:='E';
ELSE
GRADE:='F';
END IF;
IF GRADE='F' THEN
DBMS_OUTPUT.PUT_LINE('SORRY!! YOU FAILED');
ELSE
DBMS_OUTPUT.PUT_LINE('CONGRATS, YOUR GRADE IS '||GRADE);
END IF;
END;
/
/*OUTPUT1

SQL> @exp2
Enter value for mark: 82
old   5: MARK:=&MARK;
new   5: MARK:=82;
CONGRATS, YOUR GRADE IS B

PL/SQL procedure successfully completed.
OUTPUT2

SQL> @exp2
Enter value for mark: 45
old   5: MARK:=&MARK;
new   5: MARK:=45;
SORRY!! YOU FAILED

PL/SQL procedure successfully completed.
*/


