/*PROGRAM*/
SET SERVEROUTPUT ON;
DECLARE
TYPE MARKS IS VARRAY(5) OF NUMBER NOT NULL;
MARKS_1 MARKS:=MARKS(70,75,68,85,90);
MARKS_2 MARKS:=MARKS(85,65,100,67,70);
TOT_MARKS NUMBER;
I NUMBER;
LIM NUMBER;
BEGIN
LIM:=5;
FOR I  IN 1..LIM LOOP
TOT_MARKS:=MARKS_1(I)+MARKS_2(I);
DBMS_OUTPUT.PUT_LINE('TOTAL MARKS OF STUDENT'||I||': '||TOT_MARKS);
END LOOP;
END;
/
/*OUTPUT
SQL> @exp3
TOTAL MARKS OF STUDENT1: 155
TOTAL MARKS OF STUDENT2: 140
TOTAL MARKS OF STUDENT3: 168
TOTAL MARKS OF STUDENT4: 152
TOTAL MARKS OF STUDENT5: 160
*/

